### ISSUE TITLE
Grants rank to players current world.

### ISSUE THREAD

**Issue by MasonD3V** [Demeng7215/RankGrantPlus#6]
Alright let me explain.

Granting a user a rank will grant it to the world theyre currently in.
Formatted like: /pex user {playername} group set {rankname} {worldname}
And it sets their group in @world, when you want it to be set normally: /pex user {playername} group set {rankname}.

TLDR: Don't let ranks be set for specific worlds but for all worlds.

**Comment by Demeng7215** [comment]
Issue noted, thanks for reporting.

**Comment by Demeng7215** [comment]
Should be fixed after 3.0.
