### ISSUE TITLE
doesn't work on permex

### ISSUE THREAD

**Issue by DarrenSanders123** [Demeng7215/RankGrantPlus#8]
when i do /grant <player> 
it opens the menu of aveable ranks. but when i click on one it closes and doesn't give the rank
how can I fix this

**Comment by Demeng7215** [comment]
Thanks, I'll update, test, and finalize this week.

**Comment by Demeng7215** [comment]
Can I please have your full server log, version, and plugins?

**Comment by DarrenSanders123** [comment]
thx for the fast response i switched to ultrapermissions and it was a bug of my other  plugin SimpleKitPvP it blocked  the gui because it used netherstar as a kit menu
so it selected the kit when i clicked at it 
so pex wasn’t the problem

**Comment by DarrenSanders123** [comment]
but it works now

**Comment by Demeng7215** [comment]
Alright, glad it's working for you now :)
